# Generated by Django 5.0.1 on 2024-09-04 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neurodivergente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('neurodivergente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.neurodivergente')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('interesses', models.TextField(max_length=255)),
                ('profissao', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('neurodivergente', models.ManyToManyField(to='persona.neurodivergente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problemas', models.ManyToManyField(blank=True, to='persona.problemas')),
            ],
        ),
        migrations.CreateModel(
            name='Solucoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('por_que_resolver', models.TextField()),
                ('exemplo_texto', models.TextField()),
                ('exemplo_foto', models.ImageField(blank=True, null=True, upload_to='exemplos/')),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.problemas')),
            ],
        ),
    ]
